# Generated by Django 5.1.2 on 2024-10-19 17:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_product_full_slogan_alter_product_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='full_slogan',
        ),
    ]
