# Generated by Django 5.1.2 on 2024-10-19 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_product_full_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slogan',
            field=models.TextField(max_length=35),
        ),
    ]
