# Generated by Django 5.1.2 on 2024-10-19 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_product_slogan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='slogan',
            field=models.TextField(max_length=15),
        ),
    ]
