# Generated by Django 5.1.2 on 2024-10-19 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_product_rating_product_rating_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='rating_count',
        ),
        migrations.AlterField(
            model_name='product',
            name='slogan',
            field=models.TextField(max_length=50),
        ),
    ]
